
version: '3'
services: 
  jupyter:
    image: jupyter/tensorflow-notebook 
    container_name: jupyter
    restart: always
    ports: 
      - "8888:8888"  
    volumes: 
      - ./:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=""
      
